# Stage 1: Build the application
FROM node:20-slim AS builder
WORKDIR /app

# Install build dependencies
COPY package*.json ./
RUN npm install

# Copy source and build
COPY . .
RUN npm run build

# Stage 2: Production runner
FROM node:20-slim AS runner
WORKDIR /app

# Set production environment
ENV NODE_ENV=production
ENV PORT=3000
ENV HOSTNAME="0.0.0.0"

# Install production system dependencies: python3 and ffmpeg
RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    ffmpeg \
    && rm -rf /var/lib/apt/lists/*

# Set up link for python
RUN ln -s /usr/bin/python3 /usr/bin/python

# Install yt-dlp globally
RUN python3 -m pip install --break-system-packages yt-dlp

# Create directory for downloads
RUN mkdir -p tmp-downloads/.jobs && chmod -R 777 tmp-downloads

# Copy standalone build from builder
COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static
COPY --from=builder /app/public ./public

# Expose the port
EXPOSE 3000

# Start the application using code generated by standalone build
CMD ["node", "server.js"]
